// import "./globals.css";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Provider from "./_trpc/provider";
// import Navbar from "@/components/Navbar";
// import { ServerThemeProvider } from "next-themes";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Test App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Provider>
//           <div className="container">
//             <Navbar />
//             {children}
//           </div>
//         </Provider>
//       </body>
//     </html>
//   );
// }
import "./globals.css";
import { ThemeProvider } from "../components/ThemeProvider";
import Navbar from "@/components/Navbar";
import { Separator } from "@/components/ui/separator";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class">
          <Provider>
            <Navbar />
            <Separator />
            <main className="container">{children}</main>
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
