import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TrpcClientProvider from "../components/providers/TrpcClientProvider";
import Navbar from "@/components/Navbar/Navbar";
import { ThemeProvider } from "../components/providers/ThemeProvider";
import { Separator } from "@/components/ui/separator";
import AuthProvider from "@/components/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Test App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <TrpcClientProvider>
            <ThemeProvider attribute="class" defaultTheme="dark">
              <div className="min-h-screen grid" style={{ gridTemplateRows: "auto auto 1fr" }}>
                <Navbar />
                <Separator />
                <div className="container">{children}</div>
              </div>
            </ThemeProvider>
          </TrpcClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
