import Navbar from "@/components/Navbar/Navbar";
import AuthProvider from "@/components/providers/AuthProvider";
import { Separator } from "@/components/ui/separator";
import { parse } from "@/hooks/utils";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import TrpcClientProvider from "../components/providers/TrpcClientProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Test App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const theme = cookies().get("dark-theme")?.value;
  const themeClass = theme ? (parse(theme) ? "dark" : "") : "dark";

  return (
    <html lang="en">
      <body className={themeClass}>
        <AuthProvider>
          <TrpcClientProvider>
            <div className="min-h-screen grid" style={{ gridTemplateRows: "auto auto 1fr" }}>
              <Navbar />
              <Separator />
              <div className="container">{children}</div>
            </div>
          </TrpcClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
